
# ==============================================================================
# PAGE SETTINGS
# ==============================================================================

baseurl = "https://toddyamakawa.github.io/"
languageCode = "en-us"
title = "Todd Yamakawa Resume"
theme = "orbit"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true


[params]

	description = "Hugo Responsive Resume/CV Theme for Developers"
	author = "Pavel Kanyshev"

# Theme styles

	# The original template comes with 6 colour schemes. You may choose styles below.
	# "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
	# are available. Also the source LESS files are included so
	# it’s quick and easy to change the styling and colour scheme.

	styles = "todd-resume.css"


# ==============================================================================
# SIDEBAR SECTIONS
# ==============================================================================

	# --- Profile ---
	[params.profile]
		name = "Todd Yamakawa"
		tagline = "Computer Engineer"
		avatar = "profile.jpg"

	# --- Contact section ---
	[params.contact]
		enable = true

		[[params.contact.list]]
		class = "email"
		icon = "fa-envelope"
		url = "mailto: todd@yamakawa.dev"
		# TODO title = "john.doe@website.com"
		title = "john.doe@website.com"

		# REVISIT: Phone
		#[[params.contact.list]]
		#class = "phone"
		#icon = "fa-phone"
		#url = "tel:+1234567890"
		#title = "+1234567890"

		# TODO: Website
		[[params.contact.list]]
		class = "website"
		icon = "fa-globe"
		url = "//portfoliosite.com"
		title = "portfoliosite.com"

		[[params.contact.list]]
		class = "linkedin"
		icon = "fa-linkedin"
		url = "//linkedin.com/in/toddyamakawa"
		title = "linkedin.com/in/toddyamakawa"

		[[params.contact.list]]
		class = "github"
		icon = "fa-github"
		url = "//github.com/toddyamakawa"
		title = "github.com/toddyamakawa"

		# REVISIT: Twitter
		#[[params.contact.list]]
		#class = "twitter"
		#icon = "fa-twitter"
		#url = "//twitter.com/username"
		#title = "@twittername"

	# --- Education Section ---
	[params.education]
		enable = true
		title = "Education"

		[[params.education.list]]
		degree = "BS in Electrical Engineering"
		college = "University of Hawaiʻi at Mānoa"
		dates = "2009 - 2012"

	# --- Interests Section ---
	[params.interests]
		enable = true
		title = "Interests"

		[[params.interests.list]]
		interest = "Speedcubing"

		[[params.interests.list]]
		interest = "Toastmasters"

	# --- Languages Section ---
	[params.language]
		enable = true
		title = "Languages"

		[[params.language.list]]
		language = "English"
		level = "Native"


# ==============================================================================
# MAIN BODY SECTIONS
# ==============================================================================

	# --- Summary section ---
	[params.summary]
		enable = true
		icon = "fa-user"
		title = "Career Profile"
		summary = "**Summarise your career here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu."

	# --- Experiences section ---
	[params.experiences]
		enable = true
		icon = "fa-briefcase"
		title = "Experiences"

		[[params.jobs.list]]
		position = "Senior Design Engineer"
		dates = "2015 - Present"
		company = "Startup Hubs, San Francisco"
		details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

		[[params.jobs.list]]
		position = "Senior Software Engineer"
		dates = "2013 - 2015"
		company = "Google, London"
		details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

		[[params.jobs.list]]
		position = "UI Developer"
		dates = "2012 - 2014"
		company = "Amazon, London"
		details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

	# Projects section
	[params.projects]
		enable = true
		icon = "fa-archive"
		title = "Projects"
		intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

		[[params.projects.list]]
		title = "Hugrid"
		url = "https://github.com/aerohub/hugrid"
		tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

		[[params.projects.list]]
		title = "Simple FAQ Theme for Hugo"
		url = "https://github.com/aerohub/hugo-faq-theme"
		tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

		[[params.projects.list]]
		title = "Hugo Identity"
		url = "https://github.com/aerohub/hugo-identity-theme"
		tagline = "Little profile/card-style template for Hugo."

		[[params.projects.list]]
		title = "Orbit"
		url = "https://github.com/aerohub/hugo-orbit-theme"
		tagline = "Hugo Resume/CV Theme for Developers."

		[[params.projects.list]]
		title = "Resume"
		url = "https://github.com/toddyamakawa/resume"
		tagline = "My resume."

	# --- Skills Section ---
	[params.skills]
		enable = true
		icon = "fa-rocket"
		title = "Skills & Proficiency"

		[[params.skills.list]]
		skill = "Ruby"
		level = "90%"

		[[params.skills.list]]
		skill = "Bash"
		level = "90%"

		[[params.skills.list]]
		skill = "Angular"
		level = "95%"

		[[params.skills.list]]
		skill = "HTML5 & CSS"
		level = "95%"

		[[params.skills.list]]
		skill = "Ruby on Rails"
		level = "75%"

		[[params.skills.list]]
		skill = "Sketch & Photoshop"
		level = "60%"

	# Footer section

	# The original template is released under the Creative Commons Attribution 3.0 License.
	# Please keep the original attribution link when using for your own project.
	# If you'd like to use the template without the attribution,
	# you can check out other license options via template author's website: themes.3rdwavemedia.com
	#
	# As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

	[params.footer]
		copyright = ""

